let MACHINES=[],selected=null,condition="";
const $=id=>document.getElementById(id);
fetch("machines.json").then(r=>r.json()).then(x=>MACHINES=x);
function show(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(id).classList.add("active");if(id==="admin")renderAdmin("open")}
function cleanId(s){return (s||"").toUpperCase().replace(/[^A-Z0-9]/g,"")}
function lookup(){const id=cleanId($("machineId").value);selected=MACHINES.find(m=>m.id===id);$("machineId").value=id;$("machineCard").innerHTML=selected?`<b>${selected.label} — ${selected.name}</b><br>${selected.make} ${selected.model}<br>Serial/PIN: ${selected.serial||"Not recorded"}`:"Machine not found. Check the Equipment ID."}
function setCondition(v,b){condition=v;document.querySelectorAll(".seg button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");$("reasonWrap").classList.toggle("hidden",v==="Runnable")}
function loadJobs(){return JSON.parse(localStorage.getItem("cervicepro_jobs")||"[]")}function saveJobs(x){localStorage.setItem("cervicepro_jobs",JSON.stringify(x))}
async function submitFault(){lookup();if(!selected)return alert("Load a valid machine first.");if(!$("fault").value.trim())return alert("Describe the fault.");if(!condition)return alert("Select the machine condition.");
const files=[...$("media").files].map(f=>({name:f.name,type:f.type,size:f.size}));
const job={id:"WO-"+Date.now(),created:new Date().toISOString(),status:"open",machine:selected,hours:$("hours").value,condition,conditionReason:$("conditionReason").value,fault:$("fault").value.trim(),media:files};
let jobs=loadJobs();jobs.unshift(job);saveJobs(jobs);notify("CervicePro","Fault submitted for "+selected.label);postBackend("fault",job);alert("Fault report submitted.");$("machineId").value=$("hours").value=$("fault").value=$("conditionReason").value="";$("media").value="";selected=null;condition="";show("home")}
function adminLogin(){const p=prompt("Administrator password");if(p===window.CERVICEPRO_CONFIG.ADMIN_PASSWORD)show("admin");else if(p!==null)alert("Incorrect password")}
function renderStats(jobs){const now=new Date(),month=now.getMonth(),year=now.getFullYear();let cost=jobs.filter(j=>j.status==="completed"&&new Date(j.completed).getMonth()===month&&new Date(j.completed).getFullYear()===year).reduce((a,j)=>a+(j.totalCost||0),0);$("stats").innerHTML=`<div class=stat><b>${jobs.filter(j=>j.status==="open").length}</b><br>Open repairs</div><div class=stat><b>$${cost.toFixed(2)}</b><br>Month spent</div><div class=stat><b>$${Math.max(0,window.CERVICEPRO_CONFIG.MONTHLY_BUDGET-cost).toFixed(2)}</b><br>Budget remaining</div><div class=stat><b>${MACHINES.length}</b><br>Machines</div>`}
function esc(s){return String(s||"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function renderAdmin(filter){const jobs=loadJobs();renderStats(jobs);const list=jobs.filter(j=>j.status===filter);$("adminList").innerHTML=list.length?list.map(j=>`<article class="job ${j.status}"><b>${j.machine.label} — ${esc(j.machine.name)}</b><br><small>${new Date(j.created).toLocaleString()}</small><p>${esc(j.fault)}</p><p>Condition: ${esc(j.condition)} ${j.hours?`• Hours: ${esc(j.hours)}`:""}</p>${j.status==="open"?`<button class=small onclick="openFinish('${j.id}')">Finalize repair</button>`:`<p><b>Repair:</b> ${esc(j.repair)}<br><b>Root cause:</b> ${esc(j.rootCause)}<br><b>Cost:</b> $${Number(j.totalCost||0).toFixed(2)}</p>`}</article>`).join(""):"<div class=card>No records in this section.</div>"}
function renderMachines(){const jobs=loadJobs();renderStats(jobs);$("adminList").innerHTML=MACHINES.map(m=>{const mj=jobs.filter(j=>j.machine.id===m.id),repeat=mj.filter(j=>j.status==="completed").length>=2;return `<article class=job><b>${m.label} — ${esc(m.name)}</b><br>${esc(m.make)} ${esc(m.model)}<br>Serial: ${esc(m.serial||"Not recorded")}<br>Work orders: ${mj.length}${repeat?" • ⚠ Review for repeat failures":""}</article>`}).join("")}
function openFinish(id){$("finishId").value=id;$("finishDialog").showModal()}
function completeWorkOrder(){let jobs=loadJobs(),j=jobs.find(x=>x.id===$("finishId").value);if(!j)return;j.status="completed";j.completed=new Date().toISOString();j.technician=$("tech").value;j.repair=$("repair").value;j.rootCause=$("rootCause").value;j.actualFix=$("actualFix").value;j.confidence=$("confidence").value;j.partsCost=Number($("partsCost").value||0);j.laborCost=Number($("laborCost").value||0);j.totalCost=j.partsCost+j.laborCost;saveJobs(jobs);notify("CervicePro","Repair completed for "+j.machine.label);postBackend("completed",j);setTimeout(()=>renderAdmin("completed"),100)}
function notify(t,b){if("Notification"in window){if(Notification.permission==="granted")new Notification(t,{body:b});else Notification.requestPermission()}}
function postBackend(event,data){const url=window.CERVICEPRO_CONFIG.BACKEND_URL;if(!url)return;fetch(url,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain"},body:JSON.stringify({event,data})}).catch(()=>{})}
let deferredPrompt;addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("installBtn").classList.remove("hidden")});$("installBtn").onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$("installBtn").classList.add("hidden")}}
if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js");